#-------------------------#
# 此处配置已全部迁移Nacos Config配置中心
#-------------------------#



#server:
#  port: 58001
#  servlet:
#    context-path: /api
#spring:
#  jackson:
#    time-zone: GMT+8
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      url: jdbc:postgresql://127.0.0.1:5432/manux?currentSchema=pms
#      username: postgres
#      password: 12345678
#      driver-class-name: org.postgresql.Driver
#      # 连接池-初始大小
#      initial-size: 10
#      # 连接池-最大连接数
#      max-active: 100
#      # 最大等待时间
#      max-wait: 60000
#      # 连接池-最小空闲数
#      min-idle: 10
#      #检测空闲连接
#      test-while-idle: true
#      #最小空闲时间
#      min-evictable-idel-time-millis: 300000
#
#  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
#  redis:
#    host: 127.0.0.1
#    port: 6379 # 端口
#    database: 0 # 数据库索引
##    password: 123456 # 密码，建议生产环境开启
#
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志