server:
  port: 58000
  servlet:
    context-path: /api/infra
spring:
  servlet:
    multipart:
      # 最大可上传文件大小
      max-file-size: 10MB
  jackson:
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/manux?currentSchema=infra
      username: postgres
      password: 12345678
      driver-class-name: org.postgresql.Driver
      # 连接池-初始大小
      initial-size: 10
      # 连接池-最大连接数
      max-active: 100
      # 最大等待时间
      max-wait: 60000
      # 连接池-最小空闲数
      min-idle: 10
      #检测空闲连接
      test-while-idle: true
      #最小空闲时间
      min-evictable-idel-time-millis: 300000
mybatis-plus:
  # 配置mapper.xml文件的路径
  mapper-locations: classpath*:top/hondaman/cloud/**/mapper/*Mapper.xml
  global-config:
    # 不显式设置默认为1
    # 0-IGNORED 表示忽略该字段的空值判断，即无论实体对象的值为空还是非空，都会进行新增、更新操作。
    # 1-NOT_NULL 表示字段不能为空，如果实体对象的值为空，则不会进行新增、更新操作。
    # 2-NOT_EMPTY 表示字段不能为空字符串或 null 值，如果实体对象的值为空字符串或 null，则不会进行新增、更新操作。
    field-strategy: 1