spring:
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - #PMS
          id: pms
          uri: http://127.0.0.1:58001
          predicates:
            - Path=/api/pms/**
        ## 测试用
        - id: ganhua-local
          uri: http://127.0.0.1:8089
          predicates:
            - Path=/api/test/**
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/system 前缀